export enum eventTypes {
  ROOM_CONNECT = 'ROOM_CONNECT',
  STATE_CHANGE = 'STATE_CHANGE',
  TIMER_CHANGE = 'TIMER_CHANGE',
  CARD_CHANGE = 'CARD_CHANGE',
  SHOW_CARDS = 'SHOW_CARDS',
  START_VOTING = 'START_VOTING',
  STOP_VOTING = 'STOP_VOTING',
  RESET_CARDS = 'RESET_CARDS',
  PROMOTE_TO_LEADER = 'PROMOTE_TO_LEADER',
  DISCONNECT = 'disconnect',
}
