module.exports = {
  ROOM_CONNECT: 'ROOM_CONNECT',
  STATE_CHANGE: 'STATE_CHANGE',
  TIMER_CHANGE: 'TIMER_CHANGE',
  CARD_CHANGE: 'CARD_CHANGE',
  SHOW_CARDS: 'SHOW_CARDS',
  START_VOTING: 'START_VOTING',
  STOP_VOTING: 'STOP_VOTING',
};
